remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Exametrika]
description: [The Exametrika package is designed for test data engineering and corresponds to the text by Shojima (2022).]