pacman::p_load(styler, devtools, rhub)
styler::style_pkg()
devtools::document()
devtools::spell_check()
devtools::check()
# rhub::rhub_doctor()
rhub::rhub_check(platforms = c("linux", "macos", "macos-arm64", "windows"))
devtools::check_win_devel(email = "kosugitti@gmail.com")

devtools::release()
